module.exports = {
  introSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
